development:
  adapter:  mysql
  database: pdns_dev
  host:     localhost
  username: root
  password: 

test:
  adapter:  mysql
  database: pdns_test
  host:     localhost
  username: root
  password: 
